waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
#  default_dwa_limit_vel: 1.0
  default_local_inflation: 0.20 
  default_global_inflation: 0.5 
 # default_trajectory_param: 1.0
  default_trajectory_limit_vel: 1.0 

  areas:
    - name: "test"
      start_id: registed_0_1654678923563628537
      end_id: registed_0_1654679322742326305
      properties:
        - key: global_inflation
          value: 0.7
        - key: local_inflation
          value: 0
#        - key: trajectory_param
 #         value: 0
        - key: trajectory_limit_vel
          value: 0.3

